
package gui;

import java.awt.Dimension;
import java.awt.Point;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import javax.swing.JViewport;
import javax.swing.SwingUtilities;

import control.Control;

import map.Map;

/**
 * The GUI class, which extends JFrame, and provides the graphical user interface
 * of the software.
 */
public class Gui extends javax.swing.JFrame {

	private static final long serialVersionUID = 1986063334983370079L;
	private Map map;
    private Control control;
    private StringBuffer buf;

    /**
     * Creates new form Gui
     */
    public Gui(Control control) {
        this.control = control;
	this.map = control.getMap();
	this.control.gui = this;
        this.buf = new StringBuffer();
        initComponents();
    }
    /**
     * Print to the graphical console
     * @param text the text to write to the console
     * @param color the the color to style the text with
     */
    public void printToGuiConsole(final String text, final String color) {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                String formatText = "<br><span color='#008000'> $: </span>" + "<span color='" + color + "'>" + text + "</span";
                buf.append(formatText);
                jtConsole.setText(buf.toString());

            }
        });

    }
    /**
     * Center the JMapPanel within its JScrollPane
     */
    private void centerMap() {
        JViewport vp = jscrMap.getViewport();
        Dimension vs = vp.getExtentSize();
        vp.setViewPosition(new Point(JMapPanel.panelSize / 2 - vs.width / 2,
                JMapPanel.panelSize / 2 - vs.height / 2));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpMode = new javax.swing.ButtonGroup();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jscrMap = new javax.swing.JScrollPane();
        jMapPanel = new JMapPanel(map);
        jIntCollection = new javax.swing.JInternalFrame();
        jpCollection = new javax.swing.JPanel();
        jpCollectionArea = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jtX1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtX2 = new javax.swing.JTextField();
        jtY1 = new javax.swing.JTextField();
        jtY2 = new javax.swing.JTextField();
        jbtnCollect = new javax.swing.JButton();
        jIntMode = new javax.swing.JInternalFrame();
        jpMode = new javax.swing.JPanel();
        jRadSolo = new javax.swing.JRadioButton();
        jRadMulti = new javax.swing.JRadioButton();
        jIntExplore = new javax.swing.JInternalFrame();
        jbtnExplore = new javax.swing.JButton();
        jIntSave = new javax.swing.JInternalFrame();
        jpSaveMap = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jtFilename = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jbtnSave = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jbtnSaveMapInstance = new javax.swing.JButton();
        jbtnDeleteMapInstance = new javax.swing.JButton();
        jIntConsole = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtConsole = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Team Babbage SEG Group Project");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jIntMap.setIconifiable(true);
        jIntMap.setMaximizable(true);
        jIntMap.setTitle("Map");
        jIntMap.setVisible(true);

        jscrMap.setBackground(new java.awt.Color(128, 128, 128));

        jMapPanel.setBackground(new java.awt.Color(128, 128, 128));
        jMapPanel.setMinimumSize(new java.awt.Dimension(1000, 1000));
        jMapPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMapPanelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jMapPanelLayout = new javax.swing.GroupLayout(jMapPanel);
        jMapPanel.setLayout(jMapPanelLayout);
        jMapPanelLayout.setHorizontalGroup(
            jMapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jMapPanelLayout.setVerticalGroup(
            jMapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );

        jscrMap.setViewportView(jMapPanel);

        javax.swing.GroupLayout jIntMapLayout = new javax.swing.GroupLayout(jIntMap.getContentPane());
        jIntMap.getContentPane().setLayout(jIntMapLayout);
        jIntMapLayout.setHorizontalGroup(
            jIntMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jscrMap, javax.swing.GroupLayout.DEFAULT_SIZE, 1009, Short.MAX_VALUE)
        );
        jIntMapLayout.setVerticalGroup(
            jIntMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jscrMap, javax.swing.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
        );

        jIntMap.setBounds(320, 60, 690, 690);
        jDesktopPane1.add(jIntMap, javax.swing.JLayeredPane.DEFAULT_LAYER);
        try {
            jIntMap.setMaximum(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        jIntCollection.setIconifiable(true);
        jIntCollection.setTitle("Collection");
        jIntCollection.setVisible(true);

        jLabel3.setText("x1:");

        jtX1.setText("-7");

        jLabel4.setText("x2:");

        jLabel5.setText("y1:");

        jLabel6.setText("y2:");

        jtX2.setText("-6");

        jtY1.setText("3");

        jtY2.setText("2");

        javax.swing.GroupLayout jpCollectionAreaLayout = new javax.swing.GroupLayout(jpCollectionArea);
        jpCollectionArea.setLayout(jpCollectionAreaLayout);
        jpCollectionAreaLayout.setHorizontalGroup(
            jpCollectionAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCollectionAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCollectionAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpCollectionAreaLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtX2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpCollectionAreaLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtX1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCollectionAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCollectionAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtY1, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(jtY2))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jpCollectionAreaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel3, jLabel4, jLabel5, jLabel6});

        jpCollectionAreaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jtX1, jtX2, jtY1, jtY2});

        jpCollectionAreaLayout.setVerticalGroup(
            jpCollectionAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCollectionAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCollectionAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jtY1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCollectionAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jtY2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpCollectionAreaLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel3, jLabel4, jLabel5, jLabel6});

        jbtnCollect.setText("COLLECT");
        jbtnCollect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCollectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpCollectionLayout = new javax.swing.GroupLayout(jpCollection);
        jpCollection.setLayout(jpCollectionLayout);
        jpCollectionLayout.setHorizontalGroup(
            jpCollectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpCollectionArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCollectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnCollect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpCollectionLayout.setVerticalGroup(
            jpCollectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCollectionLayout.createSequentialGroup()
                .addComponent(jpCollectionArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnCollect)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jIntCollectionLayout = new javax.swing.GroupLayout(jIntCollection.getContentPane());
        jIntCollection.getContentPane().setLayout(jIntCollectionLayout);
        jIntCollectionLayout.setHorizontalGroup(
            jIntCollectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jIntCollectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpCollection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jIntCollectionLayout.setVerticalGroup(
            jIntCollectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jIntCollectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpCollection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jIntCollection.setBounds(10, 170, 300, 160);
        jDesktopPane1.add(jIntCollection, javax.swing.JLayeredPane.PALETTE_LAYER);

        jIntMode.setIconifiable(true);
        jIntMode.setTitle("Mode");
        jIntMode.setVisible(true);

        btnGrpMode.add(jRadSolo);
        jRadSolo.setSelected(true);
        jRadSolo.setText("SOLO");
        jRadSolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadSoloActionPerformed(evt);
            }
        });

        btnGrpMode.add(jRadMulti);
        jRadMulti.setText("MULTI");
        jRadMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadMultiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpModeLayout = new javax.swing.GroupLayout(jpMode);
        jpMode.setLayout(jpModeLayout);
        jpModeLayout.setHorizontalGroup(
            jpModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpModeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadMulti)
                .addGap(217, 217, 217))
            .addGroup(jpModeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadSolo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpModeLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jRadMulti, jRadSolo});

        jpModeLayout.setVerticalGroup(
            jpModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpModeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadSolo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadMulti)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jIntModeLayout = new javax.swing.GroupLayout(jIntMode.getContentPane());
        jIntMode.getContentPane().setLayout(jIntModeLayout);
        jIntModeLayout.setHorizontalGroup(
            jIntModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jIntModeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpMode, javax.swing.GroupLayout.PREFERRED_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );
        jIntModeLayout.setVerticalGroup(
            jIntModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jIntModeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpMode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jIntMode.setBounds(10, 50, 140, 120);
        jDesktopPane1.add(jIntMode, javax.swing.JLayeredPane.PALETTE_LAYER);

        jIntExplore.setIconifiable(true);
        jIntExplore.setTitle("Explore");
        jIntExplore.setVisible(true);

        jbtnExplore.setText("EXPLORE");
        jbtnExplore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExploreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jIntExploreLayout = new javax.swing.GroupLayout(jIntExplore.getContentPane());
        jIntExplore.getContentPane().setLayout(jIntExploreLayout);
        jIntExploreLayout.setHorizontalGroup(
            jIntExploreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jIntExploreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnExplore, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );
        jIntExploreLayout.setVerticalGroup(
            jIntExploreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jIntExploreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnExplore)
                .addContainerGap())
        );

        jIntExplore.setBounds(170, 50, 140, 120);
        jDesktopPane1.add(jIntExplore, javax.swing.JLayeredPane.PALETTE_LAYER);

        jIntSave.setIconifiable(true);
        jIntSave.setTitle("Save Map");
        jIntSave.setVisible(true);

        jLabel8.setText("Filename:");

        jtFilename.setText("map1");

        jLabel9.setText(".png");

        jbtnSave.setText("SAVE IMAGE");
        jbtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSaveActionPerformed(evt);
            }
        });

        jbtnSaveMapInstance.setText("Save Map");
        jbtnSaveMapInstance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSaveMapInstanceActionPerformed(evt);
            }
        });

        jbtnDeleteMapInstance.setText("Delete Map");
        jbtnDeleteMapInstance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteMapInstanceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jbtnSaveMapInstance, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnDeleteMapInstance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnSaveMapInstance)
                    .addComponent(jbtnDeleteMapInstance))
                .addContainerGap())
        );

        javax.swing.GroupLayout jpSaveMapLayout = new javax.swing.GroupLayout(jpSaveMap);
        jpSaveMap.setLayout(jpSaveMapLayout);
        jpSaveMapLayout.setHorizontalGroup(
            jpSaveMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSaveMapLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpSaveMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpSaveMapLayout.createSequentialGroup()
                        .addGroup(jpSaveMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnSave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpSaveMapLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtFilename, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                .addGap(9, 9, 9)
                                .addComponent(jLabel9)))
                        .addContainerGap())))
        );
        jpSaveMapLayout.setVerticalGroup(
            jpSaveMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSaveMapLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpSaveMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtFilename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(27, 27, 27)
                .addComponent(jbtnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jIntSaveLayout = new javax.swing.GroupLayout(jIntSave.getContentPane());
        jIntSave.getContentPane().setLayout(jIntSaveLayout);
        jIntSaveLayout.setHorizontalGroup(
            jIntSaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jIntSaveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpSaveMap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jIntSaveLayout.setVerticalGroup(
            jIntSaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jIntSaveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpSaveMap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jIntSave.setBounds(10, 330, 300, 190);
        jDesktopPane1.add(jIntSave, javax.swing.JLayeredPane.PALETTE_LAYER);

        jIntConsole.setIconifiable(true);
        jIntConsole.setMaximizable(true);
        jIntConsole.setResizable(true);
        jIntConsole.setTitle("Console");
        jIntConsole.setVisible(true);

        jtConsole.setEditable(false);
        jtConsole.setContentType("text/html"); // NOI18N
        jScrollPane1.setViewportView(jtConsole);

        javax.swing.GroupLayout jIntConsoleLayout = new javax.swing.GroupLayout(jIntConsole.getContentPane());
        jIntConsole.getContentPane().setLayout(jIntConsoleLayout);
        jIntConsoleLayout.setHorizontalGroup(
            jIntConsoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
        );
        jIntConsoleLayout.setVerticalGroup(
            jIntConsoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
        );

        jIntConsole.setBounds(10, 520, 300, 230);
        jDesktopPane1.add(jIntConsole, javax.swing.JLayeredPane.PALETTE_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1019, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMapPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMapPanelMouseClicked
        centerMap();
    }//GEN-LAST:event_jMapPanelMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        centerMap();
    }//GEN-LAST:event_formWindowOpened

    private void jbtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSaveActionPerformed
        Save.toPNG(map, jtFilename.getText() + ".png");
    }//GEN-LAST:event_jbtnSaveActionPerformed

    private void jbtnCollectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCollectActionPerformed
        try{
			double x1 = Double.parseDouble(jtX1.getText());
			double y1 = Double.parseDouble(jtY1.getText());
			double x2 = Double.parseDouble(jtX2.getText());
			double y2 = Double.parseDouble(jtY2.getText());
			control.collect(x1, y1, x2, y2);
		} catch (NumberFormatException e){
			e.printStackTrace();
		}
    }//GEN-LAST:event_jbtnCollectActionPerformed

    private void jRadMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadMultiActionPerformed
        control.switchToMulti();
    }//GEN-LAST:event_jRadMultiActionPerformed

    private void jRadSoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadSoloActionPerformed
        control.switchToSolo();
    }//GEN-LAST:event_jRadSoloActionPerformed

    private void jbtnExploreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExploreActionPerformed
        control.explore();
    }//GEN-LAST:event_jbtnExploreActionPerformed

    private void jbtnSaveMapInstanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSaveMapInstanceActionPerformed
        try {
        	File f = new File("map.instance");
            //Write to file
            FileOutputStream fos = new FileOutputStream(f);
            //Write using ObjectOutputStream
            ObjectOutputStream o = new ObjectOutputStream(fos);
            //Write map instance to disk
            o.writeObject(control.getMap());
             this.printToGuiConsole("Map instance saved.", "#00C000");
            
        } catch (FileNotFoundException ex) {
            this.printToGuiConsole("Error writing Map instance. File not found.", "#FF0000");
        } catch (IOException ex) {
            this.printToGuiConsole("Error writing Map instance. IO Exception.", "#FF0000");
        }
       
    }//GEN-LAST:event_jbtnSaveMapInstanceActionPerformed

    private void jbtnDeleteMapInstanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteMapInstanceActionPerformed
           File f = new File("map.instance");
           if(f.exists()) {
               f.delete();
               this.printToGuiConsole("Map instance deleted.", "#FF8000");
           }
           else {
                 this.printToGuiConsole("No saved Map instance. Nothing to delete.", "#00C000");
           }
       
    }//GEN-LAST:event_jbtnDeleteMapInstanceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui(new Control()).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrpMode;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JInternalFrame jIntCollection;
    private javax.swing.JInternalFrame jIntConsole;
    private javax.swing.JInternalFrame jIntExplore;
    private final javax.swing.JInternalFrame jIntMap = new javax.swing.JInternalFrame();
    private javax.swing.JInternalFrame jIntMode;
    private javax.swing.JInternalFrame jIntSave;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jMapPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadMulti;
    private javax.swing.JRadioButton jRadSolo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnCollect;
    private javax.swing.JButton jbtnDeleteMapInstance;
    private javax.swing.JButton jbtnExplore;
    private javax.swing.JButton jbtnSave;
    private javax.swing.JButton jbtnSaveMapInstance;
    private javax.swing.JPanel jpCollection;
    private javax.swing.JPanel jpCollectionArea;
    private javax.swing.JPanel jpMode;
    private javax.swing.JPanel jpSaveMap;
    private javax.swing.JScrollPane jscrMap;
    private javax.swing.JTextPane jtConsole;
    private javax.swing.JTextField jtFilename;
    private javax.swing.JTextField jtX1;
    private javax.swing.JTextField jtX2;
    private javax.swing.JTextField jtY1;
    private javax.swing.JTextField jtY2;
    // End of variables declaration//GEN-END:variables
}
