include "exploresensor.inc"

# You may edit the definition of robot_ranger.  
# You can change the position and direction of the exploresensors,
# add additional exploresensors or remove exploresensors.  Your 
# robot may possess up to 16 exploresensors (not more).  Do not
# remove the include line.

define robot_ranger ranger 
(
   exploresensor ( pose [ 0.000  0.000 0.2   -30] )
   exploresensor ( pose [ 0.000  0.000 0.2   -25] )
   exploresensor ( pose [ 0.000  0.000 0.2   -20] )
   exploresensor ( pose [ 0.000  0.000 0.2   -15] )
   exploresensor ( pose [ 0.000  0.000 0.2   -10] )
   exploresensor ( pose [ 0.000  0.000 0.2   -5] )
   exploresensor ( pose [ 0.000  0.000 0.2   0] )
   exploresensor ( pose [ 0.000  0.000 0.2   5] )
   exploresensor ( pose [ 0.000  0.000 0.2   10] )
   exploresensor ( pose [ 0.000  0.000 0.2   15] )
   exploresensor ( pose [ 0.000  0.000 0.2   20] )
   exploresensor ( pose [ 0.000  0.000 0.2   25] )
   exploresensor ( pose [ 0.000  0.000 0.2   30] )
   exploresensor ( pose [ 0.000  0.000 0.2   90] )
   exploresensor ( pose [ 0.000  0.000 0.2   180] )
   exploresensor ( pose [ 0.000  0.000 0.2   -90] )
)
